before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

    goarch:
      - amd64
      - arm
      - arm64

    ldflags:
      - -X 'main.version={{.Version}}'

archives:
  - replacements:
      darwin: macOS

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^refactor:'

release:
  name_template: "{{.ProjectName}}-v{{.Version}}"

brews:
  - name: glenv
    tap:
      owner: kiwicom
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/kiwicom/glenv
    description: jump into repository folder and GitLab env. variables are automatically loaded into your shell
