before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^refactor:'

release:
  github:
    owner: kiwicom
    name: glenv
  name_template: "{{.ProjectName}}-v{{.Version}}"

brews:
  - name: glenv
    github:
      owner: kiwicom
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/kiwicom/glenv
    description: jump into repository folder and GitLab env. variables are automatically loaded into your shell
